# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mp3_player.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 527)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: #76a3ad;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 341, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #76a3ad;\n"
"border: 1px solid #1f3a40;\n"
"border-radius: 15px;\n"
"background: #1f3a40;\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 450, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background: #99bcc4;\n"
"    color: #30393b;\n"
"}\n"
"QPushButton: hover{\n"
"    background: #8daeb5;\n"
"}\n"
"QPushButton: pressed{\n"
"        background: #8daeb5;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 450, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background: #99bcc4;\n"
"    color: #30393b;\n"
"}\n"
"QPushButton: hover{\n"
"    background: #8daeb5;\n"
"}\n"
"QPushButton: pressed{\n"
"        background: #8daeb5;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(610, 120, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background: #99bcc4;\n"
"    color: #30393b;\n"
"}\n"
"QPushButton: hover{\n"
"    background: #8daeb5;\n"
"}\n"
"QPushButton: pressed{\n"
"        background: #8daeb5;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(20, 120, 581, 321))
        self.listWidget.setStyleSheet("background: #30393b;\n"
"color: #99bcc4;\n"
"border: 1px solid #99bcc4;\n"
"border-style: outset;")
        self.listWidget.setObjectName("listWidget")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Music APP"))
        self.pushButton.setText(_translate("MainWindow", "Играть"))
        self.pushButton_2.setText(_translate("MainWindow", "Стоп"))
        self.pushButton_4.setText(_translate("MainWindow", "Скачать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
